### ISSUE TITLE
Unable to save configuration

### ISSUE THREAD

**Issue by zhang8473** [a-rodin/qstardict#29] opened 2019-02-18 03:58 UTC
qstardict 1.3 installed from Ubuntu 18.04 market
Change config and click OK, it opens another qstardict instance. After close them all, the config file is not modified and the config is saved nowhere.

I checked the permissions of the .config/qstardict. No problem. Current user is just the owner.

**Comment by a-rodin** [comment] 2019-02-18 07:53
In version 1.3 there is a bug with config file path (see #23), so actually it is located at `~/.config/Unknown Organization/qstardict.conf`. This issue with config file is fixed in the `master` version, so that config file now is `~/.config/qstardict/qstardict.conf`.

Regarding another instance: it doesn't open another instance, but shows the tray icon multiple times because of [this](https://forum.qt.io/topic/62137/qsystemtrayicon-ubuntu-15-10) Qt5/Gnome Shell bug. The problem is that `QSystemTray::hide()` method doesn't work, so that the tray icon stays after its call. And when the tray icon is recreated after config change, the previous instance still stays visible. Maybe there is a possible workaround for this though.

**Comment by a-rodin** [comment] 2019-02-22 08:06
I've added a workaround  0dce437ee64b6548ca26d5ba05d16c4dcd465666 for tray icon, so that it is not recreated when settings are saved.

Now you can try the updated version from master. The build dependencies for Ubuntu can be found here: https://github.com/a-rodin/qstardict/blob/master/.travis.yml#L8.

**Closed** 2019-03-03 16:46 UTC
Labels: bug

**Comment by a-rodin** [comment] 2019-03-06 05:30
@zhang8473 It looks like there also was another issue that could be related to problems with saving the configuration: the popup shortcut was intercepted even if it was disabled. Now it is fixed, so if the popup shortcut is disabled then it is not intercepted.
